export type Language = 'en' | 'ne' | 'hi' | 'tamang' | 'newar' | 'maithili' | 'magar' | 'rai';

export const languages: Record<Language, { name: string; nativeName: string }> = {
  en: { name: 'English', nativeName: 'English' },
  ne: { name: 'Nepali', nativeName: 'नेपाली' },
  hi: { name: 'Hindi', nativeName: 'हिन्दी' },
  tamang: { name: 'Tamang', nativeName: 'तामाङ' },
  newar: { name: 'Newar', nativeName: 'नेवारी' },
  maithili: { name: 'Maithili', nativeName: 'मैथिली' },
  magar: { name: 'Magar', nativeName: 'मगर' },
  rai: { name: 'Rai', nativeName: 'राई' },
};

// Nepal Provinces
export const nepalProvinces = [
  { name: 'Koshi Province', nepaliName: 'कोशी प्रदेश', capital: 'Biratnagar' },
  { name: 'Madhesh Province', nepaliName: 'मधेश प्रदेश', capital: 'Janakpur' },
  { name: 'Bagmati Province', nepaliName: 'बागमती प्रदेश', capital: 'Hetauda' },
  { name: 'Gandaki Province', nepaliName: 'गण्डकी प्रदेश', capital: 'Pokhara' },
  { name: 'Lumbini Province', nepaliName: 'लुम्बिनी प्रदेश', capital: 'Butwal' },
  { name: 'Karnali Province', nepaliName: 'कर्णाली प्रदेश', capital: 'Birendranagar' },
  { name: 'Sudurpashchim Province', nepaliName: 'सुदूरपश्चिम प्रदेश', capital: 'Godawari' },
];

// Nepal Districts by Province (all 77 districts)
export const nepalDistricts: Record<string, string[]> = {
  'Koshi Province': ['Bhojpur', 'Dhankuta', 'Ilam', 'Jhapa', 'Khotang', 'Morang', 'Okhaldhunga', 'Panchthar', 'Sankhuwasabha', 'Solukhumbu', 'Sunsari', 'Taplejung', 'Terhathum', 'Udayapur'],
  'Madhesh Province': ['Saptari', 'Siraha', 'Dhanusha', 'Mahottari', 'Sarlahi', 'Rautahat', 'Bara', 'Parsa'],
  'Bagmati Province': ['Sindhuli', 'Ramechhap', 'Dolakha', 'Bhaktapur', 'Dhading', 'Kathmandu', 'Kavrepalanchok', 'Lalitpur', 'Nuwakot', 'Rasuwa', 'Sindhupalchok', 'Chitwan', 'Makwanpur'],
  'Gandaki Province': ['Baglung', 'Gorkha', 'Kaski', 'Lamjung', 'Manang', 'Mustang', 'Myagdi', 'Nawalpur', 'Parbat', 'Syangja', 'Tanahun'],
  'Lumbini Province': ['Kapilvastu', 'Parasi', 'Rupandehi', 'Palpa', 'Arghakhanchi', 'Gulmi', 'Rolpa', 'Rukum East', 'Pyuthan', 'Dang', 'Banke', 'Bardiya'],
  'Karnali Province': ['Dolpa', 'Humla', 'Jumla', 'Kalikot', 'Mugu', 'Salyan', 'Surkhet', 'Dailekh', 'Jajarkot', 'Rukum West'],
  'Sudurpashchim Province': ['Kailali', 'Achham', 'Doti', 'Bajhang', 'Bajura', 'Kanchanpur', 'Dadeldhura', 'Baitadi', 'Darchula'],
};

// Ward numbers for different municipality types
export const wardNumbersByType: Record<'metro' | 'sub-metro' | 'municipality' | 'rural', number[]> = {
  'metro': Array.from({ length: 35 }, (_, i) => i + 1), // 1-35 wards for metropolitan cities
  'sub-metro': Array.from({ length: 23 }, (_, i) => i + 1), // 1-23 wards for sub-metropolitan cities
  'municipality': Array.from({ length: 15 }, (_, i) => i + 1), // 1-15 wards for municipalities
  'rural': Array.from({ length: 9 }, (_, i) => i + 1), // 1-9 wards for rural municipalities
};

// Get wards for a specific municipality
export const getWardsForMunicipality = (municipalityType: 'metro' | 'sub-metro' | 'municipality' | 'rural'): number[] => {
  return wardNumbersByType[municipalityType];
};

// Municipality ward data with exact ward counts (key municipalities)
export const municipalityWardCounts: Record<string, number> = {
  // Metropolitan Cities
  'Kathmandu Metropolitan City': 32,
  'Lalitpur Metropolitan City': 29,
  'Biratnagar Metropolitan City': 19,
  'Pokhara Metropolitan City': 33,
  'Bharatpur Metropolitan City': 29,
  // Sub-Metropolitan Cities
  'Itahari Sub-Metropolitan City': 20,
  'Dharan Sub-Metropolitan City': 20,
  'Janakpur Sub-Metropolitan City': 27,
  'Butwal Sub-Metropolitan City': 19,
  'Dhangadhi Sub-Metropolitan City': 19,
  'Kalaiya Sub-Metropolitan City': 27,
  'Jitpur Simara Sub-Metropolitan City': 23,
  'Ghorahi Sub-Metropolitan City': 19,
  'Tulsipur Sub-Metropolitan City': 19,
  'Nepalgunj Sub-Metropolitan City': 23,
  // Regular Municipalities (sample)
  'Kirtipur Municipality': 10,
  'Tokha Municipality': 11,
  'Chandragiri Municipality': 15,
  'Budhanilkantha Municipality': 13,
  'Bhaktapur Municipality': 10,
  'Damak Municipality': 11,
  'Birtamod Municipality': 11,
};

// Helper function to get exact ward count for a municipality
export const getWardCount = (municipalityName: string, municipalityType: 'metro' | 'sub-metro' | 'municipality' | 'rural'): number => {
  if (municipalityWardCounts[municipalityName]) {
    return municipalityWardCounts[municipalityName];
  }
  // Default ward counts by type
  switch (municipalityType) {
    case 'metro': return 32;
    case 'sub-metro': return 20;
    case 'municipality': return 12;
    case 'rural': return 7;
    default: return 9;
  }
};

// Generate ward options for a municipality
export const generateWardOptions = (municipalityName: string, municipalityType: 'metro' | 'sub-metro' | 'municipality' | 'rural'): { value: number; label: string; nepaliLabel: string }[] => {
  const wardCount = getWardCount(municipalityName, municipalityType);
  return Array.from({ length: wardCount }, (_, i) => ({
    value: i + 1,
    label: `Ward ${i + 1}`,
    nepaliLabel: `वडा ${i + 1}`,
  }));
};

// Nepal Municipalities (Palikas) by District - Sample key municipalities
export const nepalMunicipalities: Record<string, { name: string; nepaliName: string; type: 'metro' | 'sub-metro' | 'municipality' | 'rural'; wardCount?: number }[]> = {
  // Koshi Province
  'Jhapa': [
    { name: 'Bhadrapur Municipality', nepaliName: 'भद्रपुर नगरपालिका', type: 'municipality' },
    { name: 'Birtamod Municipality', nepaliName: 'विर्तामोड नगरपालिका', type: 'municipality' },
    { name: 'Mechinagar Municipality', nepaliName: 'मेचीनगर नगरपालिका', type: 'municipality' },
    { name: 'Damak Municipality', nepaliName: 'दमक नगरपालिका', type: 'municipality' },
    { name: 'Arjundhara Municipality', nepaliName: 'अर्जुनधारा नगरपालिका', type: 'municipality' },
    { name: 'Kankai Municipality', nepaliName: 'कन्काई नगरपालिका', type: 'municipality' },
    { name: 'Shivasatakshi Municipality', nepaliName: 'शिवशताक्षी नगरपालिका', type: 'municipality' },
    { name: 'Gauradaha Municipality', nepaliName: 'गौरादह नगरपालिका', type: 'municipality' },
  ],
  'Morang': [
    { name: 'Biratnagar Metropolitan City', nepaliName: 'विराटनगर महानगरपालिका', type: 'metro' },
    { name: 'Sundarharaicha Municipality', nepaliName: 'सुन्दरहरैचा नगरपालिका', type: 'municipality' },
    { name: 'Belbari Municipality', nepaliName: 'बेलबारी नगरपालिका', type: 'municipality' },
    { name: 'Pathari Shanischare Municipality', nepaliName: 'पथरी शनिश्चरे नगरपालिका', type: 'municipality' },
    { name: 'Urlabari Municipality', nepaliName: 'उर्लाबारी नगरपालिका', type: 'municipality' },
    { name: 'Rangeli Municipality', nepaliName: 'रंगेली नगरपालिका', type: 'municipality' },
    { name: 'Letang Municipality', nepaliName: 'लेटाङ नगरपालिका', type: 'municipality' },
    { name: 'Ratuwamai Municipality', nepaliName: 'रतुवामाई नगरपालिका', type: 'municipality' },
  ],
  'Sunsari': [
    { name: 'Itahari Sub-Metropolitan City', nepaliName: 'इटहरी उपमहानगरपालिका', type: 'sub-metro' },
    { name: 'Dharan Sub-Metropolitan City', nepaliName: 'धरान उपमहानगरपालिका', type: 'sub-metro' },
    { name: 'Inaruwa Municipality', nepaliName: 'इनरुवा नगरपालिका', type: 'municipality' },
    { name: 'Duhabi Municipality', nepaliName: 'दुहबी नगरपालिका', type: 'municipality' },
    { name: 'Ramdhuni Municipality', nepaliName: 'रामधुनी नगरपालिका', type: 'municipality' },
    { name: 'Barahakshetra Municipality', nepaliName: 'बराहक्षेत्र नगरपालिका', type: 'municipality' },
  ],
  'Ilam': [
    { name: 'Ilam Municipality', nepaliName: 'इलाम नगरपालिका', type: 'municipality' },
    { name: 'Deumai Municipality', nepaliName: 'देउमाई नगरपालिका', type: 'municipality' },
    { name: 'Mai Municipality', nepaliName: 'माई नगरपालिका', type: 'municipality' },
    { name: 'Suryodaya Municipality', nepaliName: 'सूर्योदय नगरपालिका', type: 'municipality' },
    { name: 'Phakphokthum Rural Municipality', nepaliName: 'फाकफोकथुम गाउँपालिका', type: 'rural' },
    { name: 'Sandakpur Rural Municipality', nepaliName: 'सन्दकपुर गाउँपालिका', type: 'rural' },
  ],
  // Madhesh Province
  'Dhanusha': [
    { name: 'Janakpur Sub-Metropolitan City', nepaliName: 'जनकपुर उपमहानगरपालिका', type: 'sub-metro' },
    { name: 'Chhireshwornath Municipality', nepaliName: 'छिरेश्वरनाथ नगरपालिका', type: 'municipality' },
    { name: 'Ganeshman Charnath Municipality', nepaliName: 'गणेशमान चारनाथ नगरपालिका', type: 'municipality' },
    { name: 'Dhanushadham Municipality', nepaliName: 'धनुषाधाम नगरपालिका', type: 'municipality' },
    { name: 'Nagarain Municipality', nepaliName: 'नगराइन नगरपालिका', type: 'municipality' },
    { name: 'Bideha Municipality', nepaliName: 'विदेह नगरपालिका', type: 'municipality' },
    { name: 'Mithila Municipality', nepaliName: 'मिथिला नगरपालिका', type: 'municipality' },
    { name: 'Sahidnagar Municipality', nepaliName: 'शहीदनगर नगरपालिका', type: 'municipality' },
  ],
  'Saptari': [
    { name: 'Rajbiraj Municipality', nepaliName: 'राजबिराज नगरपालिका', type: 'municipality' },
    { name: 'Kanchanrup Municipality', nepaliName: 'कञ्चनरुप नगरपालिका', type: 'municipality' },
    { name: 'Bodebarsain Municipality', nepaliName: 'बोदेबरसाईन नगरपालिका', type: 'municipality' },
    { name: 'Dakneshwori Municipality', nepaliName: 'डाक्नेश्वरी नगरपालिका', type: 'municipality' },
    { name: 'Hanumannagar Kankalini Municipality', nepaliName: 'हनुमाननगर कंकालिनी नगरपालिका', type: 'municipality' },
    { name: 'Khadak Municipality', nepaliName: 'खडक नगरपालिका', type: 'municipality' },
  ],
  'Bara': [
    { name: 'Kalaiya Sub-Metropolitan City', nepaliName: 'कलैया उपमहानगरपालिका', type: 'sub-metro' },
    { name: 'Jitpur Simara Sub-Metropolitan City', nepaliName: 'जीतपुर सिमरा उपमहानगरपालिका', type: 'sub-metro' },
    { name: 'Kolhabi Municipality', nepaliName: 'कोल्हबी नगरपालिका', type: 'municipality' },
    { name: 'Nijgadh Municipality', nepaliName: 'निजगढ नगरपालिका', type: 'municipality' },
    { name: 'Mahagadhimai Municipality', nepaliName: 'महागढीमाई नगरपालिका', type: 'municipality' },
  ],
  // Bagmati Province
  'Kathmandu': [
    { name: 'Kathmandu Metropolitan City', nepaliName: 'काठमाडौं महानगरपालिका', type: 'metro' },
    { name: 'Kirtipur Municipality', nepaliName: 'कीर्तिपुर नगरपालिका', type: 'municipality' },
    { name: 'Nagarjun Municipality', nepaliName: 'नागार्जुन नगरपालिका', type: 'municipality' },
    { name: 'Kageshwori Manohara Municipality', nepaliName: 'कागेश्वरी मनोहरा नगरपालिका', type: 'municipality' },
    { name: 'Tokha Municipality', nepaliName: 'टोखा नगरपालिका', type: 'municipality' },
    { name: 'Chandragiri Municipality', nepaliName: 'चन्द्रागिरी नगरपालिका', type: 'municipality' },
    { name: 'Budhanilkantha Municipality', nepaliName: 'बुढानिलकण्ठ नगरपालिका', type: 'municipality' },
    { name: 'Tarakeshwor Municipality', nepaliName: 'तारकेश्वर नगरपालिका', type: 'municipality' },
    { name: 'Gokarneshwor Municipality', nepaliName: 'गोकर्णेश्वर नगरपालिका', type: 'municipality' },
    { name: 'Shankharapur Municipality', nepaliName: 'शंखरापुर नगरपालिका', type: 'municipality' },
    { name: 'Dakshinkali Municipality', nepaliName: 'दक्षिणकाली नगरपालिका', type: 'municipality' },
  ],
  'Lalitpur': [
    { name: 'Lalitpur Metropolitan City', nepaliName: 'ललितपुर महानगरपालिका', type: 'metro' },
    { name: 'Godawari Municipality', nepaliName: 'गोदावरी नगरपालिका', type: 'municipality' },
    { name: 'Mahalaxmi Municipality', nepaliName: 'महालक्ष्मी नगरपालिका', type: 'municipality' },
    { name: 'Konjyosom Rural Municipality', nepaliName: 'कोन्ज्योसोम गाउँपालिका', type: 'rural' },
    { name: 'Bagmati Rural Municipality', nepaliName: 'बागमती गाउँपालिका', type: 'rural' },
  ],
  'Bhaktapur': [
    { name: 'Bhaktapur Municipality', nepaliName: 'भक्तपुर नगरपालिका', type: 'municipality' },
    { name: 'Changunarayan Municipality', nepaliName: 'चाँगुनारायण नगरपालिका', type: 'municipality' },
    { name: 'Madhyapur Thimi Municipality', nepaliName: 'मध्यपुर थिमी नगरपालिका', type: 'municipality' },
    { name: 'Suryabinayak Municipality', nepaliName: 'सूर्यबिनायक नगरपालिका', type: 'municipality' },
  ],
  'Chitwan': [
    { name: 'Bharatpur Metropolitan City', nepaliName: 'भरतपुर महानगरपालिका', type: 'metro' },
    { name: 'Ratnanagar Municipality', nepaliName: 'रत्ननगर नगरपालिका', type: 'municipality' },
    { name: 'Kalika Municipality', nepaliName: 'कालिका नगरपालिका', type: 'municipality' },
    { name: 'Khairahani Municipality', nepaliName: 'खैरहनी नगरपालिका', type: 'municipality' },
    { name: 'Rapti Municipality', nepaliName: 'राप्ती नगरपालिका', type: 'municipality' },
    { name: 'Madi Municipality', nepaliName: 'माडी नगरपालिका', type: 'municipality' },
    { name: 'Ichchhakamana Rural Municipality', nepaliName: 'इच्छाकामना गाउँपालिका', type: 'rural' },
  ],
  // Gandaki Province
  'Kaski': [
    { name: 'Pokhara Metropolitan City', nepaliName: 'पोखरा महानगरपालिका', type: 'metro' },
    { name: 'Annapurna Rural Municipality', nepaliName: 'अन्नपूर्ण गाउँपालिका', type: 'rural' },
    { name: 'Machhapuchchhre Rural Municipality', nepaliName: 'माछापुच्छ्रे गाउँपालिका', type: 'rural' },
    { name: 'Madi Rural Municipality', nepaliName: 'मादी गाउँपालिका', type: 'rural' },
    { name: 'Rupa Rural Municipality', nepaliName: 'रूपा गाउँपालिका', type: 'rural' },
  ],
  'Gorkha': [
    { name: 'Gorkha Municipality', nepaliName: 'गोरखा नगरपालिका', type: 'municipality' },
    { name: 'Palungtar Municipality', nepaliName: 'पालुङटार नगरपालिका', type: 'municipality' },
    { name: 'Sulikot Rural Municipality', nepaliName: 'सुलीकोट गाउँपालिका', type: 'rural' },
    { name: 'Siranchok Rural Municipality', nepaliName: 'सिरानचोक गाउँपालिका', type: 'rural' },
    { name: 'Ajirkot Rural Municipality', nepaliName: 'अजिरकोट गाउँपालिका', type: 'rural' },
  ],
  'Baglung': [
    { name: 'Baglung Municipality', nepaliName: 'बागलुङ नगरपालिका', type: 'municipality' },
    { name: 'Jaimini Municipality', nepaliName: 'जैमिनी नगरपालिका', type: 'municipality' },
    { name: 'Dhorpatan Municipality', nepaliName: 'ढोरपाटन नगरपालिका', type: 'municipality' },
    { name: 'Galkot Municipality', nepaliName: 'गल्कोट नगरपालिका', type: 'municipality' },
  ],
  // Lumbini Province
  'Rupandehi': [
    { name: 'Butwal Sub-Metropolitan City', nepaliName: 'बुटवल उपमहानगरपालिका', type: 'sub-metro' },
    { name: 'Siddharthanagar Municipality', nepaliName: 'सिद्धार्थनगर नगरपालिका', type: 'municipality' },
    { name: 'Tilottama Municipality', nepaliName: 'तिलोत्तमा नगरपालिका', type: 'municipality' },
    { name: 'Lumbini Sanskritik Municipality', nepaliName: 'लुम्बिनी सांस्कृतिक नगरपालिका', type: 'municipality' },
    { name: 'Devdaha Municipality', nepaliName: 'देवदह नगरपालिका', type: 'municipality' },
    { name: 'Sainamaina Municipality', nepaliName: 'सैनामैना नगरपालिका', type: 'municipality' },
  ],
  'Dang': [
    { name: 'Ghorahi Sub-Metropolitan City', nepaliName: 'घोराही उपमहानगरपालिका', type: 'sub-metro' },
    { name: 'Tulsipur Sub-Metropolitan City', nepaliName: 'तुलसीपुर उपमहानगरपालिका', type: 'sub-metro' },
    { name: 'Lamahi Municipality', nepaliName: 'लमही नगरपालिका', type: 'municipality' },
    { name: 'Gadhawa Rural Municipality', nepaliName: 'गढवा गाउँपालिका', type: 'rural' },
    { name: 'Rapti Rural Municipality', nepaliName: 'राप्ती गाउँपालिका', type: 'rural' },
  ],
  'Banke': [
    { name: 'Nepalgunj Sub-Metropolitan City', nepaliName: 'नेपालगञ्ज उपमहानगरपालिका', type: 'sub-metro' },
    { name: 'Kohalpur Municipality', nepaliName: 'कोहलपुर नगरपालिका', type: 'municipality' },
    { name: 'Rapti Sonari Rural Municipality', nepaliName: 'राप्ती सोनारी गाउँपालिका', type: 'rural' },
    { name: 'Baijanath Rural Municipality', nepaliName: 'बैजनाथ गाउँपालिका', type: 'rural' },
  ],
  // Karnali Province
  'Surkhet': [
    { name: 'Birendranagar Municipality', nepaliName: 'वीरेन्द्रनगर नगरपालिका', type: 'municipality' },
    { name: 'Gurbhakot Municipality', nepaliName: 'गुर्भाकोट नगरपालिका', type: 'municipality' },
    { name: 'Bheriganga Municipality', nepaliName: 'भेरीगंगा नगरपालिका', type: 'municipality' },
    { name: 'Lekbesi Municipality', nepaliName: 'लेकबेशी नगरपालिका', type: 'municipality' },
    { name: 'Panchapuri Municipality', nepaliName: 'पञ्चपुरी नगरपालिका', type: 'municipality' },
    { name: 'Chingad Rural Municipality', nepaliName: 'चिङ्गाड गाउँपालिका', type: 'rural' },
  ],
  'Jumla': [
    { name: 'Chandannath Municipality', nepaliName: 'चन्दननाथ नगरपालिका', type: 'municipality' },
    { name: 'Tila Rural Municipality', nepaliName: 'तिला गाउँपालिका', type: 'rural' },
    { name: 'Patarasi Rural Municipality', nepaliName: 'पातारासी गाउँपालिका', type: 'rural' },
    { name: 'Tatopani Rural Municipality', nepaliName: 'तातोपानी गाउँपालिका', type: 'rural' },
  ],
  // Sudurpashchim Province
  'Kailali': [
    { name: 'Dhangadhi Sub-Metropolitan City', nepaliName: 'धनगढी उपमहानगरपालिका', type: 'sub-metro' },
    { name: 'Tikapur Municipality', nepaliName: 'टीकापुर नगरपालिका', type: 'municipality' },
    { name: 'Ghodaghodi Municipality', nepaliName: 'घोडाघोडी नगरपालिका', type: 'municipality' },
    { name: 'Lamkichuha Municipality', nepaliName: 'लम्कीचुहा नगरपालिका', type: 'municipality' },
    { name: 'Bhajani Municipality', nepaliName: 'भजनी नगरपालिका', type: 'municipality' },
    { name: 'Godawari Municipality', nepaliName: 'गोदावरी नगरपालिका', type: 'municipality' },
    { name: 'Gauriganga Municipality', nepaliName: 'गौरीगंगा नगरपालिका', type: 'municipality' },
  ],
  'Kanchanpur': [
    { name: 'Bhimdatta Municipality', nepaliName: 'भीमदत्त नगरपालिका', type: 'municipality' },
    { name: 'Punarbas Municipality', nepaliName: 'पुनर्वास नगरपालिका', type: 'municipality' },
    { name: 'Bedkot Municipality', nepaliName: 'बेदकोट नगरपालिका', type: 'municipality' },
    { name: 'Belauri Municipality', nepaliName: 'बेलौरी नगरपालिका', type: 'municipality' },
    { name: 'Krishnapur Municipality', nepaliName: 'कृष्णपुर नगरपालिका', type: 'municipality' },
  ],
};

// Get all municipalities for a district
export function getMunicipalitiesForDistrict(district: string) {
  return nepalMunicipalities[district] || [];
}

// Get all districts for a province
export function getDistrictsForProvince(province: string) {
  return nepalDistricts[province] || [];
}

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    home: 'Home',
    dashboard: 'Dashboard',
    aiAssistant: 'AI Assistant',
    myPlots: 'My Plots',
    recommendations: 'Recommendations',
    history: 'History',
    settings: 'Settings',
    adminDashboard: 'Admin Dashboard',
    
    // AI Assistant
    askAnything: 'Ask anything about farming...',
    typeMessage: 'Type your message...',
    uploadImage: 'Upload Image',
    voiceInput: 'Voice Input',
    send: 'Send',
    analyzing: 'Analyzing...',
    speakNow: 'Speak now...',
    listening: 'Listening...',
    stopListening: 'Stop listening',
    listen: 'Listen',
    stop: 'Stop',
    
    // Crop Recommendations
    getCropRecommendations: 'Get Crop Recommendations',
    soilAnalysis: 'Soil Analysis',
    weatherForecast: 'Weather Forecast',
    marketPrices: 'Market Prices',
    viewDetails: 'View Details',
    
    // Disease Detection
    scanForDisease: 'Scan for Disease',
    takePhoto: 'Take Photo',
    uploadFromGallery: 'Upload from Gallery',
    diseaseDetected: 'Disease Detected',
    healthyCrop: 'Healthy Crop',
    treatment: 'Treatment',
    
    // Common
    loading: 'Loading...',
    error: 'Error',
    retry: 'Retry',
    save: 'Save',
    cancel: 'Cancel',
    offline: 'Offline',
    online: 'Online',
    noData: 'No data available',
    clearChat: 'Clear Chat',
    cropTips: 'Crop Tips',
    
    // Nepal specific
    province: 'Province',
    district: 'District',
    village: 'Village',
    ward: 'Ward',
    municipality: 'Municipality',
    ruralMunicipality: 'Rural Municipality',
    metropolitanCity: 'Metropolitan City',
    subMetropolitanCity: 'Sub-Metropolitan City',

    // Header & Navigation
    kisanSathi: 'Kisan Sathi',
    homeNav: 'Home',
    diseaseNav: 'Disease',
    myField: 'My Field',
    krishiBazar: 'Krishi Bazar',
    aiNav: 'AI',
    getStarted: 'Get Started',
    
    // Hero Section
    heroTagline: 'Kisan Sathi – Your Farming Companion',
    heroGreeting: 'Namaste',
    heroTitle1: 'Your Farming',
    heroTitle2: 'Trusted Companion',
    heroDescription: 'Disease detection, weather info, market prices & AI farming advice — all in one place, easy and fast.',
    detectDisease: 'Detect Disease',
    viewMarketPrices: 'View Market Prices',
    farmers: 'Farmers',
    districts: 'Districts',
    aiSupport: 'AI Support',

    // Quick Actions
    whatToDoToday: 'What to do today?',
    quickAccessInfo: 'Choose a card below for quick access',
    diseaseDetection: 'Disease Detection',
    detectFromPhoto: 'Detect from photo',
    weather: 'Weather',
    weatherInfo: 'Weather info',
    aiHelper: 'AI Helper',
    agriKnowledge: 'Agricultural knowledge',
    myFieldLabel: 'My Field',
    fieldManagement: 'Field management',
    farmingGuide: 'Farming Guide',
    farmingKnowledge: 'Farming knowledge',
    todayPrice: "Today's price",

    // Simple Home 3-button
    homeAskQuestion: 'Ask Question',
    homeAskQuestionHelper: 'Ask by text or photo — get answer fast',
    homeViewAnswers: 'My Questions',
    homeViewAnswersHelper: 'See your past questions and answers',
    homeCallExpert: 'Call Krishi Expert',
    homeCallExpertHelper: 'Request a call with an agriculture expert',
    homeGreetingLine: 'How can I help you today?',
    homeSimpleTip: 'Ask in simple words. Send a clear photo for disease detection.',

    // User Bar
    settingsLabel: 'Settings',
    dashboardLabel: 'Dashboard',
    subscription: 'Subscription',
    signOut: 'Sign Out',

    // Footer
    footerDescription: 'AI-powered crop monitoring and disease detection system for Nepali farmers. Your smart farming companion.',
    platform: 'Platform',
    farmerPortal: 'Farmer Portal',
    kisanSathiAI: 'Kisan Sathi AI',
    resources: 'Resources',
    userGuide: 'User Guide',
    contactSupport: 'Contact Support',
    copyright: '© 2024 Kisan Sathi. Built for Nepali farmers.',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',

    // Farmer Dashboard
    profile: 'Profile',
    photos: 'Photos',
    healthy: 'Healthy',
    alerts: 'Alerts',
    cropDiagnosis: 'Crop Diagnosis',
    askPhoto: 'Ask photo',
    market: 'Market',
    buySell: 'Buy / Sell',
    agriKnowledgeGuide: 'Agri Knowledge',
    cropGuide: 'Crop Guide',
    farmWork: 'Farm Work',
    activitiesLog: 'Activities Log',
    fields: 'Fields',
    treatments: 'Treatments',
    capture: 'Capture',
    calendar: 'Calendar',
    offlineData: 'Offline',

    // Disease Detection Page
    diseasePageTitle: 'Disease & Pest Detection',
    diseasePageSubtitle: 'Upload a photo and AI will detect the disease/pest and suggest treatments.',
    aiInstantCheck: '🤖 AI Instant Check',
    askExpert: '👨‍🌾 Ask an Expert',
    howToUse: '📖 How to Use?',
    stepSelectCrop: 'Select Crop',
    stepTakePhoto: 'Take Photo',
    stepUpload: 'Upload',
    stepAnalysis: 'Analysis',
    stepTreatment: 'Treatment',
    stepCropType: 'Crop type',
    stepDiseased: 'Diseased part',
    stepUploadPhoto: 'Upload photo',
    stepAICheck: 'AI check',
    stepGetAdvice: 'Get advice',
    photoTipsTitle: '🐛 For good photos:',
    photoTip1: '• Take a clear, close-up photo',
    photoTip2: '• Take it in daylight',

    // Fields Page
    fieldsPageTitle: 'My Field',
    fieldsPageSubtitle: 'Field & Crop Management',
    farmingGuideBtn: 'Farming Guide',
    guideShort: 'Guide',
    newField: 'New Field',
    addShort: 'Add',
    fieldsCount: 'Fields',
    noFieldsYet: 'No fields yet',
    addFirstField: 'Add your first field',
    selectField: 'Select a field',
    selectFieldHint: 'Choose a field from the left',
    soilTest: 'Soil Test',
    addCrop: 'Add Crop',
    area: 'Area',
    cropSeasons: 'Crop Seasons',
    noCropsInField: 'No crops in this field',
    addCropBtn: 'Add Crop',
    active: 'Active',
    completed: 'Completed',
    expected: 'Expected',
    quintal: 'quintal',
    guide: 'Guide',
    end: 'End',
    addSoilTest: 'Add Soil Test',
    guideNotAvailable: 'Guide not available for this crop. Please add from admin.',
    confirmDeleteField: 'Do you want to delete this field?',

    // Market Page
    marketPageTitle: 'Krishi Bazar',
    marketPageSubtitle: 'Check today\'s prices, sell your produce',
    dailyPrices: 'Daily Prices',
    compare: 'Compare',
    farmerMarket: 'Farmer Market',
    todayAgriMarket: 'Today\'s Agriculture Market',
    dateLabel: 'Date',
    lastAvailable: 'Last Available',
    selectLocationAndCrop: 'Select location and crop',
    allProvinces: 'All Provinces',
    allDistricts: 'All Districts',
    allLocalLevels: 'All Local Levels',
    allWards: 'All Wards',
    allCrops: 'All Crops',
    selectCrop: 'Select Crop',
    clearFilters: 'Clear',
    sortBy: 'Sort by',
    sortLabel: 'Sort',
    nameAZ: 'Name (A-Z)',
    priceLowHigh: 'Price (Low → High)',
    priceHighLow: 'Price (High → Low)',
    productsFound: 'products found',
    refreshBtn: 'Refresh',
    priceAccuracyQ: 'Price accurate?',
    updated: 'Updated',
    newPrices: 'New Prices!',
    newPriceAvailable: 'New price update available!',

    // Learning Page
    learningCenter: 'Kisan Sathi Learning Center',
    learningSubtitle: 'Learn farming knowledge, take quizzes, get certificates',
    courses: 'Courses',
    myCertificates: 'My Certificates',
    viewAll: 'View All',
    startCourse: 'Start',
    minutes: 'minutes',
    noCourses: 'No courses available right now.',
    noCoursesLevel: 'No courses available for this level.',
    loginForCertificates: 'Login to view certificates.',
    login: 'Login',
    noCertificatesYet: 'You don\'t have any certificates yet.',
    completeCourseForCert: 'Complete a course to get a certificate.',
    viewCertificate: 'View Certificate',
    learnImportantInfo: 'Learn important farming information in this course.',

    // Expert Directory
    expertDirectory: 'Agricultural Expert Directory',
    expertDirectorySubtitle: 'Contact your nearest agricultural expert. Get advice on disease detection, pest control, and improved farming techniques.',
    beforeContactTitle: '📞 Before Contacting',
    beforeContact1: '• Keep photos of the problem ready',
    beforeContact2: '• Note the symptoms',
    beforeContact3: '• Keep crop and area info',
    beforeContact4: '• Call during office hours',
    nearestOfficeTitle: '🏢 Nearest Agriculture Office',
    nearestOfficeDesc: 'If your district is not listed, contact the nearest District Agriculture Development Office.',
    nationalHelpline: 'National Agriculture Helpline:',
    officeHours: '(Office hours: 10 AM - 5 PM)',

    // Profile Page
    backToDashboard: 'Back to Dashboard',
    back: 'Back',
    editProfile: 'Edit Profile',
    personalInfo: 'Personal Information',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    farmingDetails: 'Farming Details',
    mainCrops: 'Main Crops',
    landSize: 'Land Size (Hectares)',
    irrigationType: 'Irrigation Type',
    updateProfile: 'Update Profile',
    profileUpdated: 'Profile updated',
    profileSaved: 'Your profile has been saved successfully.',
    updateFailed: 'Update failed',
    profileSaveFailed: 'Failed to save profile. Please try again.',

    // KrishiMitra AI
    krishiMitraTitle: 'Krishi Mitra - AI Farming Assistant',
    krishiMitraDesc: 'Your AI-powered farming assistant for crop diseases, weather, pest management, and farming advice.',

    // Features Section (Home)
    featuresHeading: 'Complete Solution',
    featuresSubheading: 'for Farmers',
    featuresTagline: 'Modern AI combined with local knowledge',
    featPhotoUpload: 'Photo Upload',
    featPhotoUploadDesc: 'Take a photo of the affected part of your crop.',
    featAIAnalysis: 'AI Analysis',
    featAIAnalysisDesc: 'Advanced AI detects diseases and pests.',
    featReport: 'Detailed Report',
    featReportDesc: 'Detailed report and PDF download.',
    featInstantResult: 'Instant Result',
    featInstantResultDesc: 'Get results in seconds.',
    featLocationBased: 'Location Based',
    featLocationBasedDesc: 'Suggestions based on your area.',
    featExpertAdvice: 'Expert Advice',
    featExpertAdviceDesc: 'Organic and chemical treatment options.',
    featOfflineSupport: 'Offline Support',
    featOfflineSupportDesc: 'Works even without internet.',
    featExpertContact: 'Expert Contact',
    featExpertContactDesc: 'Direct contact with agricultural technicians.',

    // How It Works Section (Home)
    howItWorksTitle: 'How to',
    howItWorksHighlight: 'Use?',
    howItWorksSubtitle: 'Detect your crop problem in 3 easy steps',
    howStep1Title: 'Take a Photo',
    howStep1Desc: 'Take a clear photo of the affected leaf or fruit.',
    howStep1Tip: '💡 Take a close-up in good light',
    howStep2Title: 'AI Analysis',
    howStep2Desc: 'Our AI system identifies the problem.',
    howStep2Tip: '⚡ Results in seconds',
    howStep3Title: 'Get Report',
    howStep3Desc: 'Download detailed treatment suggestions and PDF.',
    howStep3Tip: '📄 Share on WhatsApp',
    tryNow: 'Try Now',

    // CTA Section (Home)
    ctaTitle: 'Start',
    ctaHighlight: 'Today',
    ctaDescription: 'Thousands of Nepali farmers are already benefiting from our AI service. Check your crop health today.',
    ctaDiseaseBtn: 'Detect Disease',
    ctaExpertBtn: 'Talk to Expert',
    ctaWhatsapp: 'Contact us on WhatsApp for support',

    // Disease Detector UI
    diseaseDetectorTitle: '🌿 Crop Disease & Pest Detection System',
    diseaseDetectorSubtitle: 'AI-powered disease, pest and nutrient deficiency detection',
    tabDetect: 'Detection',
    tabHistory: 'History',
    tabDatabase: 'Disease Guide',
    tabPrevention: 'Prevention',
    selectCropType: 'Select crop type:',
    selectCropPlaceholder: 'Select crop...',
    symptomDescLabel: '🎤 Describe symptoms (optional):',
    symptomDescPlaceholder: 'Example: Brown spots on leaves, leaves turning yellow...',
    stopRecording: 'Stop',
    startRecording: 'Speak',
    liveTranscript: 'Live transcript:',
    speakPrompt: 'Speak...',
    voiceNotSupported: '⚠️ Voice input not available in your browser. Use Chrome or Edge.',
    uploadCropPhoto: '📸 Upload crop photo',
    uploadPhotoSubtext: 'Take a close-up photo of the affected leaf, stem or fruit',
    openCamera: 'Open Camera',
    chooseFromGallery: 'Choose from Gallery',
    dragDropHint: 'Or drag and drop photo here',
    analyzingPhoto: 'Analyzing...',
    analyzeBtn: 'Analyze',
    cropHealthy: '✅ Crop is healthy!',
    pestDetected: '🐛 Pest detected',
    nutrientDeficiency: '🧪 Nutrient deficiency',
    diseaseIdentified: '⚠️ Disease identified',
    symptomsLabel: '🔍 Symptoms',
    treatmentMethod: '💊 Treatment Method',
    organicTreatment: '🌿 Organic Treatment:',
    biologicalControl: '🌱 Biological Control',
    naturalEnemies: 'Natural enemies:',
    trapCrops: 'Trap crops:',
    culturalPractices: 'Cultural practices:',
    preventionMeasures: '🛡️ Prevention Measures',
    expertAdviceLabel: '⚠️ Expert advice:',
    locationLabel: 'Location:',
    detectingLocation: 'Detecting...',
    detectLocation: 'Detect location',
    pdfReport: '📄 PDF Report',
    creatingPdf: 'Creating PDF...',
    saveAsPhoto: '🖼️ Save as Photo',
    creatingImage: 'Creating image...',
    downloadLabel: 'Download',
    downloadingLabel: 'Downloading...',
    whatsappWithPhoto: 'WhatsApp + Photo',
    shareOther: 'Other',
    sendToOfficer: 'Send report to agriculture officer',
    sendToOfficerShort: 'Send to officer',
    newAnalysis: '🔄 New Analysis',
    outbreakWarning: 'Disease Outbreak Warning',
    reportsIn: 'reports in',
    districtLabel: 'district',
    receiveOutbreakAlerts: 'Receive disease outbreak notifications',
    enableAlerts: 'Enable',
    loginForHistory: 'Login to view history',
    loginForHistoryDesc: 'Account needed to save your analysis history',
    analysesCount: 'analyses',
    noHistoryYet: 'No analysis history yet',
    autoSavedHint: 'Will be auto-saved when you detect diseases',
    selectCropForGuide: 'Select a crop to view its diseases and pests',
    diseasesLabel: '🦠 Diseases',
    pestsLabel: '🐛 Pests',
    symptomsShort: '🔍 Symptoms:',
    treatmentShort: '💊 Treatment:',
    preventionShort: '🛡️ Prevention:',
    controlShort: '💊 Control:',
    bioControlShort: '🌱 Biological control:',
    damageSymptoms: '🔍 Damage symptoms:',
    activeSeason: '📅 Active:',
    preventionTipsTitle: '🛡️ Disease Prevention Tips',
    preventionTipsSubtitle: 'Follow these measures to prevent crop diseases',
    importantTipsTitle: '⚠️ Important Tips',
    tip1: '• Treat immediately when disease appears',
    tip2: '• Wear safety equipment when using chemical pesticides',
    tip3: '• Contact nearest agriculture center for serious problems',
    tip4: '• Prioritize organic methods',
    pestInfoLabel: '🐛 Pest Information',
    scientificName: 'Scientific name:',
    activePeriod: 'Active period:',
    affectedCrops: 'Affected crops:',
    confidenceLabel: 'Confidence:',
    severityLow: 'Low',
    severityMedium: 'Medium',
    severityHigh: 'Severe',
    issueTypeDisease: 'Disease',
    issueTypePest: 'Pest/Insect',
    issueTypeDeficiency: 'Nutrient Deficiency',
    issueTypeHealthy: 'Healthy',
    fileTooLarge: 'File too large',
    fileSizeLimit: 'Choose a file smaller than 10 MB',
    selectPhotoFirst: 'Select a photo',
    uploadPhotoFirst: 'Upload crop photo first',
    serviceBusy: 'Service busy. Please try again later.',
    analysisFailed: 'Analysis failed',
    tryAgain: 'Please try again',
    reportDownloaded: '✅ Report downloaded!',
    fileSaved: 'File saved to your device.',
    reportDownloadFailed: 'Sorry, report download failed',
    imageDownloaded: '✅ Image downloaded!',
    reportSavedAsImage: 'Report saved as image.',
    imageDownloadFailed: 'Sorry, image download failed',
    pdfDownloaded: '✅ PDF downloaded!',
    reportSavedAsPdf: 'Report saved as PDF.',
    pdfDownloadFailed: 'Sorry, PDF download failed',
    shareSuccess: '✅ Share successful!',
    reportSharedWithImage: 'Report shared with image.',
    imageDownloadedForShare: '📥 Image downloaded',
    attachToWhatsapp: 'Attach image to WhatsApp.',
    imageShareFailed: 'Image share failed',
    textReportShared: 'Text report has been shared.',
    whatsappOpened: '✅ WhatsApp opened',
    reportReady: 'Report ready to send.',
    whatsappOpenFailed: 'Could not open WhatsApp',
    usePopupBlocker: 'Please disable popup blocker or download report to share manually.',
    whatsappShareFailed: 'WhatsApp sharing problem',
    downloadAndShare: 'Please download report and share manually.',
    voiceInputError: '🎤 Voice input error',
    recordingStopped: '✅ Recording stopped',
    voiceSaved: 'Your voice has been saved',
    startSpeaking: '🎤 Start speaking',
    speakSymptomsNepali: 'Speak symptoms in Nepali... (Microphone active)',
    cropHealthySpeech: 'Your crop looks healthy.',
    diseaseDetectedSpeech: 'Disease detected:',
    treatmentSpeech: 'Treatment:',
    cropHealthyToast: '✅ Crop is healthy!',
    diseaseDetectedToast: '⚠️ Disease detected',


    // Prevention tips
    prevTip1: 'Use disease-resistant seeds',
    prevTip2: 'Manage water properly',
    prevTip3: 'Plant crops according to season',
    prevTip4: 'Plant in well-ventilated areas',
    prevTip5: 'Inspect regularly',
    prevTip6: 'Pay attention to pest control',
    
    // Offline Data Viewer
    offlineMode: 'Offline Mode',
    lastSynced: 'Last synced:',
    syncNow: 'Sync Now',
    youAreOffline: "You're offline",
    offlineDataDesc: 'The data below is cached from your last sync.',
    cropRecommendations: 'Crop Recommendations',
    recommendationsCached: 'recommendations cached',
    noCachedRecs: 'No cached recommendations',
    recommendedCrops: 'Recommended Crops:',
    reasoning: 'Reasoning:',
    diseaseDetections: 'Disease Detections',
    analysesCached: 'analyses cached',
    noCachedAnalyses: 'No cached analyses',
    confidence: 'Confidence:',
    preventionTips: 'Prevention Tips:',
    
    // My Market Shortcut
    todayMarketPrices: "Today's Market Prices",
    selectYourMarket: 'Select Your Market',
    yourMarket: 'Your Market',
    viewTodayPrices: "View Today's Prices",
    
    // Weather Widget
    addPlotForWeather: 'Add a plot with location to see weather',
    weatherDataUnavailable: 'Unable to load weather data',
    farmingAdvisory: 'Farming Advisory',
    avgTemp: 'Avg Temp',
    rainfall: 'Rainfall',
    rainy: 'Rainy',
    days: 'days',
    
    // Outbreak Alerts
    outbreakInYourArea: 'Disease Outbreak in Your Area!',
    activeOutbreaksNepal: 'Active Disease Outbreaks in Nepal',
    yourArea: 'Your Area',
    report: 'Report',
    reports: 'Reports',
    beCareful: 'Be Careful!',
    outbreakWarningText: 'These diseases have been detected in your district. Inspect your crops regularly and treat immediately if symptoms appear.',
    
    // Disease Prediction
    diseaseTrendPrediction: 'Disease Trend Prediction',
    days30: '30 Days',
    days60: '60 Days',
    days90: '90 Days',
    rising: 'Rising',
    falling: 'Falling',
    stable: 'Stable',
    highRisk: 'High Risk',
    mediumRisk: 'Medium',
    lowRisk: 'Low',
    predictedChange: 'Predicted Change:',
    casesPerWeek: 'cases/week',
    insufficientData: 'Insufficient data for prediction',
    need7DaysData: 'Need at least 7 days of data',
    forecast7Days: '7-Day Forecast',
    forecastSubtitle: 'Estimated disease reports for next week',
    actual: 'Actual',
    forecast: 'Forecast',
    highRiskWarning: 'High Risk Warning',
    highRiskText: 'Rising trend detected in the following diseases, immediate attention required:',
    
    // Diagnosis Case Submit
    submitDiagnosis: 'Submit Disease/Pest Case',
    submitSubtitle: 'Send a photo, an agricultural expert will answer.',
    caseSubmitted: 'Case submitted successfully!',
    expertWillNotify: 'You will be notified when an expert answers.',
    preliminaryNote: 'This is a preliminary estimate only, final advice will come after expert review.',
    selectCropLabel: '1. Select Crop *',
    selectCropPlaceholder2: 'Select a crop...',
    uploadPhotoLabel: '2. Take/Upload Photo * (1-3 photos)',
    camera: 'Camera',
    gallery: 'Gallery',
    max3Photos: 'Max 3 photos only',
    photoRequired: 'Photo required',
    upload1Photo: 'Please upload at least 1 photo.',
    describeIssueLabel: '3. Describe issue briefly (Optional)',
    describePlaceholder: 'e.g., Leaves turning yellow, black spots appearing, insects seen...',
    submitDisclaimer: 'Note: This system provides preliminary estimates only. Final diagnosis and treatment are confirmed only after expert review. Use chemicals only after expert advice.',
    submitting: 'Sending...',
    submitCase: 'Submit Case',
    leafCloseup: 'Leaf Closeup',
    plantFull: 'Full Plant',
    fruitFlower: 'Fruit/Flower',
    stemRoot: 'Stem/Root',
    other: 'Other',
    
    // My Diagnosis Cases
    myCases: 'My Disease/Pest Cases',
    loginToViewCases: 'Login to view your cases',
    noCasesYet: 'No cases submitted yet',
    new: 'New',
    preliminaryEstimate: 'Preliminary Estimate',
    waitingForExpert: 'Waiting for Expert',
    expertAnswered: 'Answered',
    closed: 'Closed',
    unknownCrop: 'Unknown Crop',
    preliminaryHint: 'Preliminary Hint (AI/Rule based - Not Final)',
    expertAnswer: 'Expert Answer ✓',


    // Add Field Dialog
    addNewField: 'Add New Field',
    fieldName: 'Field Name *',
    fieldNamePlaceholder: 'Enter field name',
    orChooseOne: 'Or choose one of these:',
    moreSuggestions: 'View more suggestions',
    areaLabel: 'Area',
    unitLabel: 'Unit',
    selectLocation: 'Select Location',
    selectProvince: 'Select province',
    selectDistrict: 'Select district',
    selectLocalLevel: 'Select local level',
    selectWard: 'Select ward',
    choosePlaceholder: 'Choose...',
    wardNo: 'Ward No.',
    addingField: 'Adding...',
    addField: 'Add Field',
    ropani: 'Ropani',
    katha: 'Katha',
    bigha: 'Bigha',
    hectare: 'Hectare',

    // Field name suggestions (English)
    fieldFront: 'Front Field',
    fieldBack: 'Back Field',
    fieldUpper: 'Upper Field',
    fieldLower: 'Lower Field',
    fieldEast: 'East Field',
    fieldWest: 'West Field',
    fieldRiver: 'Riverside Field',
    fieldRoad: 'Roadside Field',
    fieldRice: 'Rice Paddy',
    fieldVegetable: 'Vegetable Garden',
    fieldFruit: 'Fruit Orchard',
    fieldMaize: 'Maize Field',
    fieldPotato: 'Potato Field',
    fieldMain: 'Main Farm',

    // Crop Guide Card
    aiGuide: 'AI Guide',
    stageLabel: 'Stage',
    topicLabel: 'Topic',
    askMoreQuestion: 'Ask more questions',
    questionPlaceholder: 'e.g.: Leaves turning yellow, what to do?',
    loadingGuide: 'Loading...',
    reloadGuide: 'Reload',
    viewGuide: 'View Guide',
    guideFailed: 'Failed to load guide. Please try later.',
    guideLoadFailed: 'Failed to load guide',
    aiSummary: 'AI Summary',
    whatToDo: 'What to do:',
    detailedInfo: 'Detailed Information:',
    stageGeneral: 'General Information',
    stageBeforeSowing: 'Before Sowing',
    stageSowing: 'Sowing Time',
    stageSeedling: 'Seedling Stage',
    stageVegetative: 'Growth Stage',
    stageFlowering: 'Flowering Time',
    stageFruiting: 'Fruiting Time',
    stagePreHarvest: 'Before Harvest',
    stagePostHarvest: 'After Harvest',
    problemGeneral: 'General Advice',
    problemDisease: 'Disease Problem',
    problemPest: 'Pest Problem',
    problemFertilizer: 'Fertilizer Related',
    problemIrrigation: 'Irrigation Related',
    problemWeather: 'Weather Related',
    problemMarket: 'Market Related',
  },
  ne: {
    // Navigation
    home: 'गृहपृष्ठ',
    dashboard: 'ड्यासबोर्ड',
    aiAssistant: 'कृषि मित्र',
    myPlots: 'मेरा खेतहरू',
    recommendations: 'सिफारिसहरू',
    history: 'इतिहास',
    settings: 'सेटिङहरू',
    adminDashboard: 'प्रशासन ड्यासबोर्ड',
    
    // AI Assistant
    askAnything: 'खेतीको बारेमा केहि पनि सोध्नुहोस्...',
    typeMessage: 'आफ्नो सन्देश टाइप गर्नुहोस्...',
    uploadImage: 'फोटो अपलोड गर्नुहोस्',
    voiceInput: 'आवाजले बोल्नुहोस्',
    send: 'पठाउनुहोस्',
    analyzing: 'विश्लेषण भइरहेको छ...',
    speakNow: 'अहिले बोल्नुहोस्...',
    listening: 'सुनिरहेको छ...',
    stopListening: 'सुन्न रोक्नुहोस्',
    listen: 'सुन्नुहोस्',
    stop: 'रोक्नुहोस्',
    
    // Crop Recommendations
    getCropRecommendations: 'बाली सिफारिस प्राप्त गर्नुहोस्',
    soilAnalysis: 'माटो विश्लेषण',
    weatherForecast: 'मौसम पूर्वानुमान',
    marketPrices: 'बजार मूल्य',
    viewDetails: 'विवरण हेर्नुहोस्',
    
    // Disease Detection
    scanForDisease: 'रोग जाँच गर्नुहोस्',
    takePhoto: 'फोटो खिच्नुहोस्',
    uploadFromGallery: 'ग्यालेरीबाट छान्नुहोस्',
    diseaseDetected: 'रोग भेटियो',
    healthyCrop: 'स्वस्थ बाली',
    treatment: 'उपचार',
    
    // Common
    loading: 'लोड हुँदैछ...',
    error: 'त्रुटि',
    retry: 'पुनः प्रयास गर्नुहोस्',
    save: 'सेभ गर्नुहोस्',
    cancel: 'रद्द गर्नुहोस्',
    offline: 'अफलाइन',
    online: 'अनलाइन',
    noData: 'डाटा उपलब्ध छैन',
    clearChat: 'च्याट खाली गर्नुहोस्',
    cropTips: 'बाली सुझाव',
    
    // Nepal specific
    province: 'प्रदेश',
    district: 'जिल्ला',
    village: 'गाउँ',
    ward: 'वडा',
    municipality: 'नगरपालिका',
    ruralMunicipality: 'गाउँपालिका',
    metropolitanCity: 'महानगरपालिका',
    subMetropolitanCity: 'उपमहानगरपालिका',

    // Header & Navigation
    kisanSathi: 'किसान साथी',
    homeNav: 'गृह',
    diseaseNav: 'रोग',
    myField: 'मेरो खेत',
    krishiBazar: 'कृषि बजार',
    aiNav: 'AI',
    getStarted: 'सुरु गर्नुहोस्',
    
    // Hero Section
    heroTagline: 'किसान साथी – तपाईँको खेतीको साथी',
    heroGreeting: 'नमस्ते',
    heroTitle1: 'तपाईँको खेतीको',
    heroTitle2: 'भरपर्दो साथी',
    heroDescription: 'रोग पहिचान, मौसम जानकारी, कृषि बजार भाउ र AI खेती सल्लाह — सबै एकै ठाउँमा, सजिलो र छिटो।',
    detectDisease: 'रोग पहिचान गर्नुहोस्',
    viewMarketPrices: 'बजार भाउ हेर्नुहोस्',
    farmers: 'किसान',
    districts: 'जिल्ला',
    aiSupport: 'AI सहायता',

    // Quick Actions
    whatToDoToday: 'आज के गर्ने?',
    quickAccessInfo: 'छिटो पहुँचको लागि तलको कार्ड छान्नुहोस्',
    diseaseDetection: 'रोग पहिचान',
    detectFromPhoto: 'फोटोबाट पहिचान',
    weather: 'मौसम',
    weatherInfo: 'मौसम जानकारी',
    aiHelper: 'AI सहायक',
    agriKnowledge: 'कृषि ज्ञान',
    myFieldLabel: 'मेरो खेत',
    fieldManagement: 'खेत व्यवस्थापन',
    farmingGuide: 'खेती गाइड',
    farmingKnowledge: 'खेती ज्ञान',
    todayPrice: 'आजको भाउ',

    // Simple Home 3-button
    homeAskQuestion: 'प्रश्न सोध्नुहोस्',
    homeAskQuestionHelper: 'लेखेर वा फोटो पठाएर — छिटो जवाफ पाउनुहोस्',
    homeViewAnswers: 'मेरा प्रश्नहरू',
    homeViewAnswersHelper: 'तपाईँका पुराना प्रश्न र जवाफहरू हेर्नुहोस्',
    homeCallExpert: 'कृषि विज्ञलाई कल गर्नुहोस्',
    homeCallExpertHelper: 'कृषि विज्ञसँग कल अनुरोध गर्नुहोस्',
    homeGreetingLine: 'आज तपाईँलाई के सहायोग चाहियो?',
    homeSimpleTip: 'सजिलो शब्दमा प्रश्न सोध्नुहोस्। रोग पहिचानको लागि स्पष्ट फोटो पठाउनुहोस्।',

    // User Bar
    settingsLabel: 'सेटिङ',
    dashboardLabel: 'ड्यासबोर्ड',
    subscription: 'सदस्यता',
    signOut: 'साइन आउट',

    // Footer
    footerDescription: 'नेपाली किसानहरूको लागि AI-संचालित बाली निगरानी र रोग पहिचान प्रणाली। तपाईँको खेतीमा स्मार्ट साथी।',
    platform: 'प्लेटफर्म',
    farmerPortal: 'किसान पोर्टल',
    kisanSathiAI: 'किसान साथी AI',
    resources: 'स्रोतहरू',
    userGuide: 'प्रयोगकर्ता गाइड',
    contactSupport: 'सम्पर्क सहायता',
    copyright: '© 2024 किसान साथी। नेपाली किसानहरूको लागि बनाइएको।',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवाका सर्तहरू',

    // Farmer Dashboard
    profile: 'प्रोफाइल',
    photos: 'फोटो',
    healthy: 'स्वस्थ',
    alerts: 'सूचना',
    cropDiagnosis: 'रोग पहिचान',
    askPhoto: 'फोटो सोध्ने',
    market: 'बजार',
    buySell: 'बेच्ने / किन्ने',
    agriKnowledgeGuide: 'कृषि ज्ञान',
    cropGuide: 'बाली गाइड',
    farmWork: 'कृषि कार्य',
    activitiesLog: 'कार्य रेकर्ड',
    fields: 'खेत',
    treatments: 'उपचार',
    capture: 'क्याप्चर',
    calendar: 'क्यालेन्डर',
    offlineData: 'अफलाइन',

    // Disease Detection Page
    diseasePageTitle: 'रोग र कीरा पहिचान',
    diseasePageSubtitle: 'फोटो अपलोड गर्नुहोस्, AI ले रोग/कीरा पत्ता लगाई उपचार सुझाव दिनेछ।',
    aiInstantCheck: '🤖 AI तुरुन्त जाँच',
    askExpert: '👨‍🌾 विज्ञलाई सोध्नुहोस्',
    howToUse: '📖 कसरी प्रयोग गर्ने?',
    stepSelectCrop: 'बाली छान्ने',
    stepTakePhoto: 'फोटो खिच्ने',
    stepUpload: 'अपलोड गर्ने',
    stepAnalysis: 'विश्लेषण',
    stepTreatment: 'उपचार',
    stepCropType: 'बाली प्रकार',
    stepDiseased: 'रोगी पात/फल',
    stepUploadPhoto: 'फोटो हाल्ने',
    stepAICheck: 'AI जाँच',
    stepGetAdvice: 'सुझाव पाउने',
    photoTipsTitle: '🐛 राम्रो फोटोको लागि:',
    photoTip1: '• नजिकबाट स्पष्ट फोटो खिच्नुहोस्',
    photoTip2: '• दिनको उज्यालोमा खिच्नुहोस्',

    // Fields Page
    fieldsPageTitle: 'मेरो खेत',
    fieldsPageSubtitle: 'खेत र बाली व्यवस्थापन',
    farmingGuideBtn: 'खेती गाइड',
    guideShort: 'गाइड',
    newField: 'नयाँ खेत',
    addShort: 'थप्ने',
    fieldsCount: 'खेतहरू',
    noFieldsYet: 'कुनै खेत छैन',
    addFirstField: 'पहिलो खेत थप्नुहोस्',
    selectField: 'खेत छान्नुहोस्',
    selectFieldHint: 'बायाँबाट खेत छान्नुहोस्',
    soilTest: 'माटो परीक्षण',
    addCrop: 'बाली थप्ने',
    area: 'क्षेत्रफल',
    cropSeasons: 'बाली सिजनहरू',
    noCropsInField: 'यस खेतमा कुनै बाली छैन',
    addCropBtn: 'बाली थप्नुहोस्',
    active: 'सक्रिय',
    completed: 'समाप्त',
    expected: 'अपेक्षित',
    quintal: 'क्विन्टल',
    guide: 'गाइड',
    end: 'समाप्त',
    addSoilTest: 'माटो परीक्षण थप्नुहोस्',
    guideNotAvailable: 'यो बालीको गाइड उपलब्ध छैन। कृपया admin बाट बाली थप्नुहोस्।',
    confirmDeleteField: 'के तपाईं यो खेत हटाउन चाहनुहुन्छ?',

    // Market Page
    marketPageTitle: 'कृषि बजार',
    marketPageSubtitle: 'आजको भाउ हेर्नुहोस्, उपज बेच्नुहोस्',
    dailyPrices: 'दैनिक भाउ',
    compare: 'तुलना',
    farmerMarket: 'किसान बजार',
    todayAgriMarket: 'आजको कृषि बजार',
    dateLabel: 'मिति',
    lastAvailable: 'अन्तिम उपलब्ध',
    selectLocationAndCrop: 'स्थान र बाली छान्नुहोस्',
    allProvinces: 'सबै प्रदेश',
    allDistricts: 'सबै जिल्ला',
    allLocalLevels: 'सबै पालिका',
    allWards: 'सबै वडा',
    allCrops: 'सबै बाली',
    selectCrop: 'बाली छान्नुहोस्',
    clearFilters: 'हटाउनुहोस्',
    sortBy: 'क्रमबद्ध:',
    sortLabel: 'क्रमबद्ध गर्नुहोस्',
    nameAZ: 'नाम (A-Z)',
    priceLowHigh: 'मूल्य (कम → धेरै)',
    priceHighLow: 'मूल्य (धेरै → कम)',
    productsFound: 'वटा उत्पादन फेला परे',
    refreshBtn: 'रिफ्रेस',
    priceAccuracyQ: 'मूल्य मिल्छ?',
    updated: 'अपडेट',
    newPrices: 'नयाँ मूल्य!',
    newPriceAvailable: 'नयाँ मूल्य अपडेट उपलब्ध छ!',

    // Learning Page
    learningCenter: 'किसान साथी सिकाइ केन्द्र',
    learningSubtitle: 'खेतीको ज्ञान सिक्नुहोस्, क्विज दिनुहोस्, प्रमाणपत्र पाउनुहोस्',
    courses: 'कोर्सहरू',
    myCertificates: 'मेरा प्रमाणपत्रहरू',
    viewAll: 'सबै हेर्नुहोस्',
    startCourse: 'सुरु गर्नुहोस्',
    minutes: 'मिनेट',
    noCourses: 'अहिले कुनै कोर्स उपलब्ध छैन।',
    noCoursesLevel: 'यो स्तरमा कुनै कोर्स उपलब्ध छैन।',
    loginForCertificates: 'प्रमाणपत्र हेर्न लगइन गर्नुहोस्।',
    login: 'लगइन गर्नुहोस्',
    noCertificatesYet: 'अहिले सम्म कुनै प्रमाणपत्र पाउनुभएको छैन।',
    completeCourseForCert: 'कोर्स पूरा गरेपछि प्रमाणपत्र पाउनुहुनेछ।',
    viewCertificate: 'प्रमाणपत्र हेर्नुहोस्',
    learnImportantInfo: 'यस कोर्समा खेती सम्बन्धी महत्वपूर्ण जानकारी सिक्नुहोस्।',

    // Expert Directory
    expertDirectory: 'कृषि प्राविधिक निर्देशिका',
    expertDirectorySubtitle: 'आफ्नो नजिकको कृषि विशेषज्ञसँग सम्पर्क गर्नुहोस्। रोग पहिचान, कीट नियन्त्रण, र उन्नत खेती प्रविधिको बारेमा विशेषज्ञ सल्लाह लिनुहोस्।',
    beforeContactTitle: '📞 सम्पर्क गर्नुअघि',
    beforeContact1: '• समस्याको फोटो तयार राख्नुहोस्',
    beforeContact2: '• लक्षणहरू नोट गर्नुहोस्',
    beforeContact3: '• बाली र क्षेत्रफल जानकारी राख्नुहोस्',
    beforeContact4: '• कार्यालय समयमा फोन गर्नुहोस्',
    nearestOfficeTitle: '🏢 नजिकको कृषि कार्यालय',
    nearestOfficeDesc: 'यदि सूचीमा तपाईंको जिल्ला छैन भने, नजिकको जिल्ला कृषि विकास कार्यालयमा सम्पर्क गर्न सक्नुहुन्छ।',
    nationalHelpline: 'राष्ट्रिय कृषि हेल्पलाइन:',
    officeHours: '(कार्यालय समय: बिहान १० - साँझ ५)',

    // Profile Page
    backToDashboard: 'ड्यासबोर्डमा फर्कनुहोस्',
    back: 'फिर्ता',
    editProfile: 'प्रोफाइल सम्पादन',
    personalInfo: 'व्यक्तिगत जानकारी',
    fullName: 'पूरा नाम',
    phoneNumber: 'फोन नम्बर',
    farmingDetails: 'खेती विवरण',
    mainCrops: 'मुख्य बालीहरू',
    landSize: 'जमिन क्षेत्रफल (हेक्टर)',
    irrigationType: 'सिँचाइ प्रकार',
    updateProfile: 'प्रोफाइल अपडेट गर्नुहोस्',
    profileUpdated: 'प्रोफाइल अपडेट भयो',
    profileSaved: 'तपाईंको प्रोफाइल सफलतापूर्वक सुरक्षित गरिएको छ।',
    updateFailed: 'अपडेट असफल भयो',
    profileSaveFailed: 'प्रोफाइल सुरक्षित गर्न असफल भयो। पुन: प्रयास गर्नुहोस्।',

    // KrishiMitra AI
    krishiMitraTitle: 'कृषि मित्र - AI खेती सहायक',
    krishiMitraDesc: 'बाली रोग, मौसम, कीरा व्यवस्थापन, र खेती सल्लाहको लागि तपाईंको AI सहायक।',

    // Features Section (Home)
    featuresHeading: 'सम्पूर्ण समाधान',
    featuresSubheading: 'किसानका लागि',
    featuresTagline: 'आधुनिक AI र स्थानीय ज्ञानको संयोजन',
    featPhotoUpload: 'फोटो अपलोड',
    featPhotoUploadDesc: 'बालीको प्रभावित भागको फोटो खिच्नुहोस्।',
    featAIAnalysis: 'AI विश्लेषण',
    featAIAnalysisDesc: 'उन्नत AI ले रोग र कीरा पहिचान गर्छ।',
    featReport: 'नेपाली रिपोर्ट',
    featReportDesc: 'विस्तृत रिपोर्ट र PDF डाउनलोड।',
    featInstantResult: 'तुरुन्त नतिजा',
    featInstantResultDesc: 'केही सेकेन्डमा नतिजा प्राप्त।',
    featLocationBased: 'स्थान आधारित',
    featLocationBasedDesc: 'तपाईंको क्षेत्र अनुसार सुझाव।',
    featExpertAdvice: 'विशेषज्ञ सुझाव',
    featExpertAdviceDesc: 'जैविक र रासायनिक उपचार विकल्प।',
    featOfflineSupport: 'अफलाइन सपोर्ट',
    featOfflineSupportDesc: 'इन्टरनेट नभएमा पनि काम गर्छ।',
    featExpertContact: 'विशेषज्ञ सम्पर्क',
    featExpertContactDesc: 'कृषि प्राविधिकसँग सिधै सम्पर्क।',

    // How It Works Section (Home)
    howItWorksTitle: 'कसरी',
    howItWorksHighlight: 'प्रयोग गर्ने?',
    howItWorksSubtitle: '३ सजिलो चरणमा तपाईंको बालीको समस्या पत्ता लगाउनुहोस्',
    howStep1Title: 'फोटो खिच्नुहोस्',
    howStep1Desc: 'बालीको प्रभावित पात वा फलको स्पष्ट फोटो खिच्नुहोस्।',
    howStep1Tip: '💡 राम्रो प्रकाशमा नजिकबाट खिच्नुहोस्',
    howStep2Title: 'AI विश्लेषण',
    howStep2Desc: 'हाम्रो AI प्रणालीले समस्या पहिचान गर्छ।',
    howStep2Tip: '⚡ केही सेकेन्डमा नतिजा',
    howStep3Title: 'रिपोर्ट पाउनुहोस्',
    howStep3Desc: 'विस्तृत उपचार सुझाव र PDF डाउनलोड गर्नुहोस्।',
    howStep3Tip: '📄 WhatsApp मा Share गर्नुहोस्',
    tryNow: 'अहिले प्रयास गर्नुहोस्',

    // CTA Section (Home)
    ctaTitle: 'आज नै',
    ctaHighlight: 'सुरु गर्नुहोस्',
    ctaDescription: 'हजारौं नेपाली किसानहरू पहिले नै हाम्रो AI सेवाको फाइदा लिइरहेका छन्। तपाईंको बालीको स्वास्थ्य जाँच गर्न आज नै सुरु गर्नुहोस्।',
    ctaDiseaseBtn: 'रोग पहिचान गर्नुहोस्',
    ctaExpertBtn: 'विशेषज्ञसँग कुरा गर्नुहोस्',
    ctaWhatsapp: 'सहयोगका लागि WhatsApp मा सम्पर्क गर्नुहोस्',

    // Disease Detector UI
    diseaseDetectorTitle: '🌿 बाली रोग र कीरा पहिचान प्रणाली',
    diseaseDetectorSubtitle: 'AI द्वारा रोग, कीरा-किट र पोषक तत्व कमी पहिचान',
    tabDetect: 'रोग पहिचान',
    tabHistory: 'इतिहास',
    tabDatabase: 'रोग पुस्तिका',
    tabPrevention: 'रोकथाम',
    selectCropType: 'बालीको प्रकार छान्नुहोस्:',
    selectCropPlaceholder: 'बाली छान्नुहोस्...',
    symptomDescLabel: '🎤 लक्षण बर्णन गर्नुहोस् (ऐच्छिक):',
    symptomDescPlaceholder: 'उदाहरण: पातमा खैरो दाग देखिएको छ, पात पहेंलो भएको छ...',
    stopRecording: 'रोक्नुहोस्',
    startRecording: 'बोल्नुहोस्',
    liveTranscript: 'लाइभ ट्रान्सक्रिप्ट:',
    speakPrompt: 'बोल्नुहोस्...',
    voiceNotSupported: '⚠️ तपाईंको ब्राउजरमा आवाज इनपुट उपलब्ध छैन। Chrome वा Edge प्रयोग गर्नुहोस्।',
    uploadCropPhoto: '📸 बालीको फोटो अपलोड गर्नुहोस्',
    uploadPhotoSubtext: 'प्रभावित पात, डाँठ वा फलको नजिकबाट फोटो खिच्नुहोस्',
    openCamera: 'क्यामेरा खोल्नुहोस्',
    chooseFromGallery: 'गेलेरीबाट छान्नुहोस्',
    dragDropHint: 'वा फोटो यहाँ ड्र्याग एन्ड ड्रप गर्नुहोस्',
    analyzingPhoto: 'विश्लेषण गर्दैछ...',
    analyzeBtn: 'विश्लेषण गर्नुहोस्',
    cropHealthy: '✅ बाली स्वस्थ छ!',
    pestDetected: '🐛 कीरा/किट पहिचान भयो',
    nutrientDeficiency: '🧪 पोषक तत्व कमी',
    diseaseIdentified: '⚠️ रोग पहिचान भयो',
    symptomsLabel: '🔍 लक्षणहरू',
    treatmentMethod: '💊 उपचार विधि',
    organicTreatment: '🌿 जैविक उपचार:',
    biologicalControl: '🌱 जैविक नियन्त्रण',
    naturalEnemies: 'प्राकृतिक शत्रुहरू:',
    trapCrops: 'ट्र्याप बाली:',
    culturalPractices: 'सांस्कृतिक विधि:',
    preventionMeasures: '🛡️ रोकथामका उपायहरू',
    expertAdviceLabel: '⚠️ विशेषज्ञ सल्लाह:',
    locationLabel: 'स्थान:',
    detectingLocation: 'पत्ता लगाउँदै...',
    detectLocation: 'स्थान पत्ता लगाउनुहोस्',
    pdfReport: '📄 PDF रिपोर्ट',
    creatingPdf: 'PDF बन्दैछ...',
    saveAsPhoto: '🖼️ फोटो सेभ',
    creatingImage: 'इमेज बन्दैछ...',
    downloadLabel: 'डाउनलोड',
    downloadingLabel: 'डाउनलोड...',
    whatsappWithPhoto: 'WhatsApp + फोटो',
    shareOther: 'अरू',
    sendToOfficer: 'कृषि अधिकारीलाई रिपोर्ट पठाउनुहोस्',
    sendToOfficerShort: 'अधिकारीलाई पठाउनु',
    newAnalysis: '🔄 नयाँ विश्लेषण गर्नुहोस्',
    outbreakWarning: 'रोग प्रकोप चेतावनी',
    reportsIn: 'रिपोर्ट',
    districtLabel: 'जिल्लामा',
    receiveOutbreakAlerts: 'रोग प्रकोप सूचना प्राप्त गर्नुहोस्',
    enableAlerts: 'सक्षम गर्नुहोस्',
    loginForHistory: 'इतिहास हेर्न लगइन गर्नुहोस्',
    loginForHistoryDesc: 'तपाईंको विश्लेषण इतिहास सुरक्षित गर्न खाता चाहिन्छ',
    analysesCount: 'विश्लेषणहरू',
    noHistoryYet: 'कुनै विश्लेषण इतिहास छैन',
    autoSavedHint: 'रोग पहिचान गर्दा स्वतः सुरक्षित हुनेछ',
    selectCropForGuide: 'बाली छानेर रोग र कीराहरूको जानकारी हेर्नुहोस्',
    diseasesLabel: '🦠 रोगहरू',
    pestsLabel: '🐛 कीरा-किटहरू',
    symptomsShort: '🔍 लक्षणहरू:',
    treatmentShort: '💊 उपचार:',
    preventionShort: '🛡️ रोकथाम:',
    controlShort: '💊 नियन्त्रण:',
    bioControlShort: '🌱 जैविक नियन्त्रण:',
    damageSymptoms: '🔍 क्षतिको लक्षण:',
    activeSeason: '📅 सक्रिय:',
    preventionTipsTitle: '🛡️ रोग रोकथामका सुझावहरू',
    preventionTipsSubtitle: 'यी उपायहरू अपनाएर बालीको रोग रोक्न सकिन्छ',
    importantTipsTitle: '⚠️ महत्त्वपूर्ण सुझाव',
    tip1: '• रोग देखिएपछि तुरुन्त उपचार गर्नुहोस्',
    tip2: '• रासायनिक औषधि प्रयोग गर्दा सुरक्षा उपकरण लगाउनुहोस्',
    tip3: '• गम्भीर समस्यामा नजिकको कृषि केन्द्रमा सम्पर्क गर्नुहोस्',
    tip4: '• जैविक उपायलाई प्राथमिकता दिनुहोस्',
    pestInfoLabel: '🐛 कीरा जानकारी',
    scientificName: 'वैज्ञानिक नाम:',
    activePeriod: 'सक्रिय समय:',
    affectedCrops: 'प्रभावित बालीहरू:',
    confidenceLabel: 'विश्वास:',
    severityLow: 'सामान्य',
    severityMedium: 'मध्यम',
    severityHigh: 'गम्भीर',
    issueTypeDisease: 'रोग',
    issueTypePest: 'कीरा/किट',
    issueTypeDeficiency: 'पोषक तत्व कमी',
    issueTypeHealthy: 'स्वस्थ',
    fileTooLarge: 'फाइल ठूलो भयो',
    fileSizeLimit: '१० MB भन्दा सानो फाइल छान्नुहोस्',
    selectPhotoFirst: 'फोटो छान्नुहोस्',
    uploadPhotoFirst: 'पहिले बालीको फोटो अपलोड गर्नुहोस्',
    serviceBusy: 'सेवा व्यस्त छ। कृपया केही समय पछि प्रयास गर्नुहोस्।',
    analysisFailed: 'विश्लेषण असफल',
    tryAgain: 'कृपया पुनः प्रयास गर्नुहोस्',
    reportDownloaded: '✅ रिपोर्ट डाउनलोड भयो!',
    fileSaved: 'फाइल तपाईंको डिभाइसमा सेभ भयो।',
    reportDownloadFailed: 'माफ गर्नुहोस्, रिपोर्ट डाउनलोड हुन सकेन',
    imageDownloaded: '✅ इमेज डाउनलोड भयो!',
    reportSavedAsImage: 'रिपोर्ट फोटोको रूपमा सेभ भयो।',
    imageDownloadFailed: 'माफ गर्नुहोस्, इमेज डाउनलोड हुन सकेन',
    pdfDownloaded: '✅ PDF डाउनलोड भयो!',
    reportSavedAsPdf: 'रिपोर्ट PDF को रूपमा सेभ भयो।',
    pdfDownloadFailed: 'माफ गर्नुहोस्, PDF डाउनलोड हुन सकेन',
    shareSuccess: '✅ Share सफल भयो!',
    reportSharedWithImage: 'रिपोर्ट इमेज सहित share भयो।',
    imageDownloadedForShare: '📥 इमेज डाउनलोड भयो',
    attachToWhatsapp: 'WhatsApp मा इमेज attach गर्नुहोस्।',
    imageShareFailed: 'इमेज share हुन सकेन',
    textReportShared: 'Text रिपोर्ट share गरिएको छ।',
    whatsappOpened: '✅ WhatsApp खुल्यो',
    reportReady: 'रिपोर्ट पठाउन तयार छ।',
    whatsappOpenFailed: 'WhatsApp खोल्न सकिएन',
    usePopupBlocker: 'कृपया popup blocker बन्द गर्नुहोस् वा रिपोर्ट डाउनलोड गरेर manually share गर्नुहोस्।',
    whatsappShareFailed: 'WhatsApp बाट पठाउन समस्या आयो',
    downloadAndShare: 'कृपया रिपोर्ट डाउनलोड गरेर manually share गर्नुहोस्।',
    voiceInputError: '🎤 आवाज इनपुट त्रुटि',
    recordingStopped: '✅ रेकर्डिङ रोकियो',
    voiceSaved: 'तपाईंको आवाज सुरक्षित भयो',
    startSpeaking: '🎤 बोल्न सुरु गर्नुहोस्',
    speakSymptomsNepali: 'नेपालीमा लक्षणहरू बोल्नुहोस्... (माइक्रोफोन सक्रिय छ)',
    cropHealthySpeech: 'तपाईंको बाली स्वस्थ देखिन्छ।',
    diseaseDetectedSpeech: 'रोग पहिचान:',
    treatmentSpeech: 'उपचार:',
    cropHealthyToast: '✅ बाली स्वस्थ छ!',
    diseaseDetectedToast: '⚠️ रोग पहिचान भयो',

    // Prevention tips
    prevTip1: 'रोग प्रतिरोधी बिउ प्रयोग गर्नुहोस्',
    prevTip2: 'पानी व्यवस्थापन राम्रो गर्नुहोस्',
    prevTip3: 'मौसम अनुसार बाली लगाउनुहोस्',
    prevTip4: 'हावा चल्ने ठाउँमा रोप्नुहोस्',
    prevTip5: 'नियमित निरीक्षण गर्नुहोस्',
    prevTip6: 'कीरा नियन्त्रणमा ध्यान दिनुहोस्',
    
    // Offline Data Viewer
    offlineMode: 'अफलाइन मोड',
    lastSynced: 'अन्तिम सिंक:',
    syncNow: 'सिंक गर्नुहोस्',
    youAreOffline: 'तपाईं अफलाइन हुनुहुन्छ',
    offlineDataDesc: 'तल भएको डाटा तपाईंको अन्तिम सिंकबाट क्यास गरिएको छ।',
    cropRecommendations: 'बाली सिफारिसहरू',
    recommendationsCached: 'सिफारिसहरू क्यास गरिएको',
    noCachedRecs: 'कुनै क्यास गरिएको सिफारिस छैन',
    recommendedCrops: 'सिफारिस गरिएका बालीहरू:',
    reasoning: 'कारण:',
    diseaseDetections: 'रोग पत्ता लगाउने',
    analysesCached: 'विश्लेषणहरू क्यास गरिएको',
    noCachedAnalyses: 'कुनै क्यास गरिएको विश्लेषण छैन',
    confidence: 'विश्वास:',
    preventionTips: 'रोकथाम सुझावहरू:',
    
    // My Market Shortcut
    todayMarketPrices: 'आजको बजार भाउ',
    selectYourMarket: 'आफ्नो बजार छान्नुहोस्',
    yourMarket: 'तपाईंको बजार',
    viewTodayPrices: 'आजको मूल्य हेर्नुहोस्',
    
    // Weather Widget
    addPlotForWeather: 'मौसम हेर्न स्थान सहित खेत थप्नुहोस्',
    weatherDataUnavailable: 'मौसम डाटा लोड गर्न सकिएन',
    farmingAdvisory: 'खेती सल्लाह',
    avgTemp: 'औसत तापक्रम',
    rainfall: 'वर्षा',
    rainy: 'वर्षा हुने',
    days: 'दिन',
    
    // Outbreak Alerts
    outbreakInYourArea: 'तपाईंको क्षेत्रमा रोग प्रकोप!',
    activeOutbreaksNepal: 'नेपालमा सक्रिय रोग प्रकोपहरू',
    yourArea: 'तपाईंको क्षेत्र',
    report: 'रिपोर्ट',
    reports: 'रिपोर्टहरू',
    beCareful: 'सावधान रहनुहोस्!',
    outbreakWarningText: 'तपाईंको जिल्लामा यी रोगहरू पहिचान भएका छन्। आफ्नो बालीको नियमित निरीक्षण गर्नुहोस् र लक्षण देखिएमा तुरुन्त उपचार गर्नुहोस्।',
    
    // Disease Prediction
    diseaseTrendPrediction: 'रोग प्रवृत्ति पूर्वानुमान',
    days30: '३० दिन',
    days60: '६० दिन',
    days90: '९० दिन',
    rising: 'बढ्दो',
    falling: 'घट्दो',
    stable: 'स्थिर',
    highRisk: 'उच्च जोखिम',
    mediumRisk: 'मध्यम',
    lowRisk: 'कम',
    predictedChange: 'अनुमानित परिवर्तन:',
    casesPerWeek: 'केस/हप्ता',
    insufficientData: 'पूर्वानुमानको लागि पर्याप्त डाटा छैन',
    need7DaysData: 'कम्तीमा ७ दिनको डाटा चाहिन्छ',
    forecast7Days: '७ दिनको पूर्वानुमान',
    forecastSubtitle: 'अगामी हप्ताको अनुमानित रोग रिपोर्ट',
    actual: 'वास्तविक',
    forecast: 'पूर्वानुमान',
    highRiskWarning: 'उच्च जोखिम चेतावनी',
    highRiskText: 'निम्न रोगहरूमा बढ्दो प्रवृत्ति देखिएको छ र तत्काल सावधानी आवश्यक छ:',
    
    // Diagnosis Case Submit
    submitDiagnosis: 'रोग/किरा जाँच पठाउनुहोस्',
    submitSubtitle: 'फोटो खिचेर पठाउनुहोस्, कृषि विज्ञले उत्तर दिनुहुनेछ।',
    caseSubmitted: 'केस सफलतापूर्वक पठाइयो!',
    expertWillNotify: 'कृषि विज्ञको उत्तर आएपछि तपाईंलाई सूचना दिइनेछ।',
    preliminaryNote: 'यो केवल प्रारम्भिक अनुमान हो, अन्तिम सल्लाह विज्ञले हेरेपछि आउनेछ।',
    selectCropLabel: '१. बाली छान्नुहोस् *',
    selectCropPlaceholder2: 'बाली छान्नुहोस्...',
    uploadPhotoLabel: '२. फोटो खिच्नुहोस् / अपलोड गर्नुहोस् * (१-३ वटा)',
    camera: 'क्यामेरा',
    gallery: 'गेलेरी',
    max3Photos: 'अधिकतम ३ फोटो मात्र',
    photoRequired: 'फोटो आवश्यक छ',
    upload1Photo: 'कम्तीमा १ वटा फोटो अपलोड गर्नुहोस्।',
    describeIssueLabel: '३. समस्या छोटकरीमा लेख्नुहोस् (ऐच्छिक)',
    describePlaceholder: 'जस्तै: पात पहेंलो भयो, काला दाग परेको छ, कीरा देखियो...',
    submitDisclaimer: 'नोट: यो प्रणालीले प्रारम्भिक अनुमान मात्र दिन्छ। अन्तिम निदान र उपचार कृषि विज्ञको जाँचपछि मात्र निश्चित हुन्छ। रसायन प्रयोग विज्ञको सल्लाहपछि मात्र गर्नुहोस्।',
    submitting: 'पठाउँदै...',
    submitCase: 'केस पठाउनुहोस्',
    leafCloseup: 'पातको नजिकको फोटो',
    plantFull: 'पूरा बिरुवा',
    fruitFlower: 'फल/फूल',
    stemRoot: 'डाँठ/गाँठ',
    other: 'अन्य',
    
    // My Diagnosis Cases
    myCases: 'मेरा रोग/किरा केसहरू',
    loginToViewCases: 'आफ्ना केसहरू हेर्न लगइन गर्नुहोस्',
    noCasesYet: 'अहिलेसम्म कुनै केस पठाइएको छैन',
    new: 'नयाँ',
    preliminaryEstimate: 'प्रारम्भिक अनुमान',
    waitingForExpert: 'विज्ञको पर्खाइमा',
    expertAnswered: 'उत्तर आएको छ',
    closed: 'बन्द',
    unknownCrop: 'अज्ञात बाली',
    preliminaryHint: 'प्रारम्भिक अनुमान (AI/Rule आधारित – अन्तिम होइन)',
    expertAnswer: 'कृषि विज्ञको उत्तर ✓',


    // Add Field Dialog
    addNewField: 'नयाँ खेत थप्नुहोस्',
    fieldName: 'खेतको नाम *',
    fieldNamePlaceholder: 'खेतको नाम लेख्नुहोस्',
    orChooseOne: 'वा यी मध्ये एउटा छान्नुहोस्:',
    moreSuggestions: 'थप सुझावहरू हेर्नुहोस्',
    areaLabel: 'क्षेत्रफल',
    unitLabel: 'एकाइ',
    selectLocation: 'स्थान छान्नुहोस्',
    selectProvince: 'प्रदेश छान्नुहोस्',
    selectDistrict: 'जिल्ला छान्नुहोस्',
    selectLocalLevel: 'पालिका छान्नुहोस्',
    selectWard: 'वडा छान्नुहोस्',
    choosePlaceholder: 'छान्नुहोस्...',
    wardNo: 'वडा नं.',
    addingField: 'थप्दै...',
    addField: 'खेत थप्नुहोस्',
    ropani: 'रोपनी',
    katha: 'कठ्ठा',
    bigha: 'बिघा',
    hectare: 'हेक्टर',

    // Field name suggestions (Nepali)
    fieldFront: 'घर अगाडिको खेत',
    fieldBack: 'घर पछाडिको खेत',
    fieldUpper: 'माथिल्लो खेत',
    fieldLower: 'तल्लो खेत',
    fieldEast: 'पूर्वी खेत',
    fieldWest: 'पश्चिमी खेत',
    fieldRiver: 'खोलाको खेत',
    fieldRoad: 'बाटोको खेत',
    fieldRice: 'धानखेत',
    fieldVegetable: 'तरकारी बारी',
    fieldFruit: 'फलफूल बारी',
    fieldMaize: 'मकै खेत',
    fieldPotato: 'आलु खेत',
    fieldMain: 'किसान खेत',

    // Crop Guide Card
    aiGuide: 'AI गाइड',
    stageLabel: 'अवस्था',
    topicLabel: 'विषय',
    askMoreQuestion: 'थप प्रश्न राख्नुहोस्',
    questionPlaceholder: 'जस्तै: पात पहेँलो भयो के गर्ने?',
    loadingGuide: 'लोड हुँदैछ...',
    reloadGuide: 'पुनः लोड गर्नुहोस्',
    viewGuide: 'गाइड हेर्नुहोस्',
    guideFailed: 'गाइड लोड गर्न असफल भयो। पछि प्रयास गर्नुहोस्।',
    guideLoadFailed: 'गाइड लोड गर्न असफल',
    aiSummary: 'AI सारांश',
    whatToDo: 'के गर्नुहोस्:',
    detailedInfo: 'विस्तृत जानकारी:',
    stageGeneral: 'सामान्य जानकारी',
    stageBeforeSowing: 'रोप्नु अघि',
    stageSowing: 'रोप्ने बेला',
    stageSeedling: 'बिरुवा अवस्था',
    stageVegetative: 'बढ्दो अवस्था',
    stageFlowering: 'फूल लाग्ने बेला',
    stageFruiting: 'फल लाग्ने बेला',
    stagePreHarvest: 'कटानी अघि',
    stagePostHarvest: 'कटानी पछि',
    problemGeneral: 'सामान्य सल्लाह',
    problemDisease: 'रोग समस्या',
    problemPest: 'किरा समस्या',
    problemFertilizer: 'मल सम्बन्धी',
    problemIrrigation: 'सिँचाइ सम्बन्धी',
    problemWeather: 'मौसम सम्बन्धी',
    problemMarket: 'बजार सम्बन्धी',
  },
  hi: {
    // Navigation
    home: 'होम',
    dashboard: 'डैशबोर्ड',
    aiAssistant: 'कृषि मित्र',
    myPlots: 'मेरे खेत',
    recommendations: 'सिफारिशें',
    history: 'इतिहास',
    settings: 'सेटिंग्स',
    adminDashboard: 'एडमिन डैशबोर्ड',
    
    // AI Assistant
    askAnything: 'खेती के बारे में कुछ भी पूछें...',
    typeMessage: 'अपना संदेश टाइप करें...',
    uploadImage: 'फोटो अपलोड करें',
    voiceInput: 'आवाज से बोलें',
    send: 'भेजें',
    analyzing: 'विश्लेषण हो रहा है...',
    speakNow: 'अब बोलें...',
    listening: 'सुन रहा है...',
    stopListening: 'सुनना बंद करें',
    listen: 'सुनें',
    stop: 'रोकें',
    
    // Crop Recommendations
    getCropRecommendations: 'फसल सिफारिश प्राप्त करें',
    soilAnalysis: 'मिट्टी विश्लेषण',
    weatherForecast: 'मौसम पूर्वानुमान',
    marketPrices: 'बाजार भाव',
    viewDetails: 'विवरण देखें',
    
    // Disease Detection
    scanForDisease: 'रोग की जांच करें',
    takePhoto: 'फोटो लें',
    uploadFromGallery: 'गैलरी से चुनें',
    diseaseDetected: 'रोग मिला',
    healthyCrop: 'स्वस्थ फसल',
    treatment: 'उपचार',
    
    // Common
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    retry: 'फिर से प्रयास करें',
    save: 'सेव करें',
    cancel: 'रद्द करें',
    offline: 'ऑफलाइन',
    online: 'ऑनलाइन',
    noData: 'डेटा उपलब्ध नहीं है',
    clearChat: 'चैट साफ करें',
    cropTips: 'फसल सुझाव',
    
    // Nepal specific
    province: 'प्रदेश',
    district: 'जिला',
    village: 'गांव',
    ward: 'वार्ड',
    municipality: 'नगरपालिका',
    ruralMunicipality: 'ग्रामीण नगरपालिका',
    metropolitanCity: 'महानगरपालिका',
    subMetropolitanCity: 'उपमहानगरपालिका',
  },
  tamang: {
    home: 'क्ह्याला',
    dashboard: 'ड्यासबोर्ड',
    aiAssistant: 'कृषि ग्याल्बो',
    myPlots: 'ङाला खेत',
    recommendations: 'सल्लाह',
    history: 'ह्युला',
    settings: 'सेटिङ',
    adminDashboard: 'प्रशासन ड्यासबोर्ड',
    askAnything: 'खेतीला बारेमा तिमीले सोद...',
    typeMessage: 'तिम्रो सन्देश टाइप ला...',
    uploadImage: 'फोटो अपलोड ला',
    voiceInput: 'आवाजले भन',
    send: 'पठाउ',
    analyzing: 'जाँच्दैछ...',
    speakNow: 'अहिले बोल...',
    listening: 'सुनिरहेको छ...',
    stopListening: 'सुन्न रोक',
    listen: 'सुन',
    stop: 'रोक',
    getCropRecommendations: 'बाली सल्लाह लिउ',
    soilAnalysis: 'माटो जाँच',
    weatherForecast: 'मौसम',
    marketPrices: 'बजार भाउ',
    viewDetails: 'विवरण हेर',
    scanForDisease: 'रोग जाँच',
    takePhoto: 'फोटो खिच',
    uploadFromGallery: 'ग्यालेरीबाट छान',
    diseaseDetected: 'रोग भेटियो',
    healthyCrop: 'राम्रो बाली',
    treatment: 'उपचार',
    loading: 'लोड हुँदैछ...',
    error: 'गल्ती',
    retry: 'फेरि गर',
    save: 'सेभ गर',
    cancel: 'रद्द गर',
    offline: 'अफलाइन',
    online: 'अनलाइन',
    noData: 'डाटा छैन',
    clearChat: 'च्याट खाली गर',
    cropTips: 'बाली सुझाव',
    province: 'प्रदेश',
    district: 'जिल्ला',
    village: 'गाउँ',
    ward: 'वडा',
    municipality: 'नगरपालिका',
    ruralMunicipality: 'गाउँपालिका',
    metropolitanCity: 'महानगरपालिका',
    subMetropolitanCity: 'उपमहानगरपालिका',
  },
  newar: {
    home: 'छेँ',
    dashboard: 'ड्यासबोर्ड',
    aiAssistant: 'कृषि सहयोगी',
    myPlots: 'जिगु खेत',
    recommendations: 'सल्लाह',
    history: 'इतिहास',
    settings: 'सेटिङ',
    adminDashboard: 'प्रशासन ड्यासबोर्ड',
    askAnything: 'खेतीया बारेय छु नं न्हय...',
    typeMessage: 'छिगु सन्देश च्वय...',
    uploadImage: 'फोटो अपलोड या',
    voiceInput: 'आवाजं भन',
    send: 'ब्वय',
    analyzing: 'जाँच जुयाच्वंगु...',
    speakNow: 'अहिले भन...',
    listening: 'न्यनाच्वंगु...',
    stopListening: 'न्यनेगु रोक',
    listen: 'न्यन',
    stop: 'रोक',
    getCropRecommendations: 'बाली सल्लाह काय',
    soilAnalysis: 'माटो जाँच',
    weatherForecast: 'हवामान',
    marketPrices: 'बजार मूल्य',
    viewDetails: 'विवरण स्वय',
    scanForDisease: 'रोग जाँच',
    takePhoto: 'फोटो काय',
    uploadFromGallery: 'ग्यालेरीं थ्वय',
    diseaseDetected: 'रोग दु',
    healthyCrop: 'स्वस्थ बाली',
    treatment: 'उपचार',
    loading: 'लोड जुयाच्वंगु...',
    error: 'भुल',
    retry: 'लय या',
    save: 'सेभ या',
    cancel: 'रद्द या',
    offline: 'अफलाइन',
    online: 'अनलाइन',
    noData: 'डाटा मदु',
    clearChat: 'च्याट लय',
    cropTips: 'बाली सुझाव',
    province: 'प्रदेश',
    district: 'जिल्ला',
    village: 'गाउँ',
    ward: 'वडा',
    municipality: 'नगरपालिका',
    ruralMunicipality: 'गाउँपालिका',
    metropolitanCity: 'महानगरपालिका',
    subMetropolitanCity: 'उपमहानगरपालिका',
  },
  maithili: {
    home: 'घर',
    dashboard: 'ड्यासबोर्ड',
    aiAssistant: 'कृषि मित्र',
    myPlots: 'हमर खेत',
    recommendations: 'सलाह',
    history: 'इतिहास',
    settings: 'सेटिङ',
    adminDashboard: 'प्रशासन ड्यासबोर्ड',
    askAnything: 'खेतीक बारेमे किछु पूछू...',
    typeMessage: 'अपन सन्देश टाइप करू...',
    uploadImage: 'फोटो अपलोड करू',
    voiceInput: 'आवाजसँ बोलू',
    send: 'पठाउ',
    analyzing: 'जाँच भ रहल अछि...',
    speakNow: 'अखन बोलू...',
    listening: 'सुनि रहल छी...',
    stopListening: 'सुनब बन्द करू',
    listen: 'सुनू',
    stop: 'बन्द करू',
    getCropRecommendations: 'फसल सलाह लिउ',
    soilAnalysis: 'माटी जाँच',
    weatherForecast: 'मौसम',
    marketPrices: 'बजार भाव',
    viewDetails: 'विवरण देखू',
    scanForDisease: 'रोग जाँच',
    takePhoto: 'फोटो खीचू',
    uploadFromGallery: 'ग्यालेरीसँ चुनू',
    diseaseDetected: 'रोग भेटल',
    healthyCrop: 'नीक फसल',
    treatment: 'इलाज',
    loading: 'लोड भ रहल अछि...',
    error: 'गलती',
    retry: 'फेर प्रयास करू',
    save: 'सेभ करू',
    cancel: 'रद्द करू',
    offline: 'अफलाइन',
    online: 'अनलाइन',
    noData: 'डाटा नहि अछि',
    clearChat: 'च्याट साफ करू',
    cropTips: 'फसल सुझाव',
    province: 'प्रदेश',
    district: 'जिल्ला',
    village: 'गाम',
    ward: 'वार्ड',
    municipality: 'नगरपालिका',
    ruralMunicipality: 'गाउँपालिका',
    metropolitanCity: 'महानगरपालिका',
    subMetropolitanCity: 'उपमहानगरपालिका',
  },
  magar: {
    home: 'घर',
    dashboard: 'ड्यासबोर्ड',
    aiAssistant: 'कृषि सहायक',
    myPlots: 'ङा खेत',
    recommendations: 'सल्लाह',
    history: 'इतिहास',
    settings: 'सेटिङ',
    adminDashboard: 'प्रशासन ड्यासबोर्ड',
    askAnything: 'खेतीला बारेमा तिमीले सोध...',
    typeMessage: 'तिम्रो सन्देश टाइप गर...',
    uploadImage: 'फोटो राख',
    voiceInput: 'आवाजले भन',
    send: 'पठाउ',
    analyzing: 'जाँच्दैछ...',
    speakNow: 'अहिले बोल...',
    listening: 'सुनिरहेको छ...',
    stopListening: 'सुन्न रोक',
    listen: 'सुन',
    stop: 'रोक',
    getCropRecommendations: 'बाली सल्लाह लिउ',
    soilAnalysis: 'माटो जाँच',
    weatherForecast: 'मौसम',
    marketPrices: 'बजार भाउ',
    viewDetails: 'विवरण हेर',
    scanForDisease: 'रोग जाँच',
    takePhoto: 'फोटो खिच',
    uploadFromGallery: 'ग्यालेरीबाट छान',
    diseaseDetected: 'रोग भेटियो',
    healthyCrop: 'राम्रो बाली',
    treatment: 'उपचार',
    loading: 'लोड हुँदैछ...',
    error: 'गल्ती',
    retry: 'फेरि गर',
    save: 'सेभ गर',
    cancel: 'रद्द गर',
    offline: 'अफलाइन',
    online: 'अनलाइन',
    noData: 'डाटा छैन',
    clearChat: 'च्याट खाली गर',
    cropTips: 'बाली सुझाव',
    province: 'प्रदेश',
    district: 'जिल्ला',
    village: 'गाउँ',
    ward: 'वडा',
    municipality: 'नगरपालिका',
    ruralMunicipality: 'गाउँपालिका',
    metropolitanCity: 'महानगरपालिका',
    subMetropolitanCity: 'उपमहानगरपालिका',
  },
  rai: {
    home: 'खिम',
    dashboard: 'ड्यासबोर्ड',
    aiAssistant: 'कृषि सहायक',
    myPlots: 'आङ खेत',
    recommendations: 'सल्लाह',
    history: 'इतिहास',
    settings: 'सेटिङ',
    adminDashboard: 'प्रशासन ड्यासबोर्ड',
    askAnything: 'खेतीको बारेमा सोध...',
    typeMessage: 'सन्देश टाइप गर...',
    uploadImage: 'फोटो राख',
    voiceInput: 'आवाजले भन',
    send: 'पठाउ',
    analyzing: 'जाँच्दैछ...',
    speakNow: 'अहिले बोल...',
    listening: 'सुनिरहेको छ...',
    stopListening: 'सुन्न रोक',
    listen: 'सुन',
    stop: 'रोक',
    getCropRecommendations: 'बाली सल्लाह लिउ',
    soilAnalysis: 'माटो जाँच',
    weatherForecast: 'मौसम',
    marketPrices: 'बजार भाउ',
    viewDetails: 'विवरण हेर',
    scanForDisease: 'रोग जाँच',
    takePhoto: 'फोटो खिच',
    uploadFromGallery: 'ग्यालेरीबाट छान',
    diseaseDetected: 'रोग भेटियो',
    healthyCrop: 'राम्रो बाली',
    treatment: 'उपचार',
    loading: 'लोड हुँदैछ...',
    error: 'गल्ती',
    retry: 'फेरि गर',
    save: 'सेभ गर',
    cancel: 'रद्द गर',
    offline: 'अफलाइन',
    online: 'अनलाइन',
    noData: 'डाटा छैन',
    clearChat: 'च्याट खाली गर',
    cropTips: 'बाली सुझाव',
    province: 'प्रदेश',
    district: 'जिल्ला',
    village: 'गाउँ',
    ward: 'वडा',
    municipality: 'नगरपालिका',
    ruralMunicipality: 'गाउँपालिका',
    metropolitanCity: 'महानगरपालिका',
    subMetropolitanCity: 'उपमहानगरपालिका',
  },
};

export function useTranslation(language: Language) {
  return (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };
}
